### ISSUE TITLE
stCancer package not working under Recent R version i.e 4.2

### ISSUE THREAD

**Issue by pratapstat** [Miaoyx323/stCancer#3]
Hi,
I'm surprised that stCancer package is not working with a recent version of R. It would be a great help if we were able to run with R version 4.2.

Best Regards,
Pratap,
Senior Bioinformatician,
A*STAR, 
Singapore.

**Comment by pratapstat** [comment]
Hi,
Any update regarding this ?

**Comment by Miaoyx323** [comment]
I'm sorry for replying to you late. We recommend that you run stCancer with R version 4.1. Dependency conflicts may exist in the latest version of R.

**Comment by pratapstat** [comment]
Thanks.I will try on R version 4.1 then.

**Comment by pratapstat** [comment]
Thanks , it's working on R version 4.1
