### ISSUE TITLE
Empty csv file for cluster 0 Differentially Expressed genes (DEG's) for all sectors

### ISSUE THREAD

**Issue by pratapstat** [Miaoyx323/stCancer#5]
Hi,
Cluster 0 was neglected in the calculation of DEGs from all tissue sectors so that the CSV file for cluster 0 will be an empty file and also the file name was not named as cluster 0 DEG's but named as cluster5.csv when there are 4 clusters in that tissue sector. Please help to resolve this issue.
<img width="1417" alt="Screenshot 2022-07-20 at 11 59 31 AM" src="https://user-images.githubusercontent.com/8164766/179894305-445c5f14-30ce-447d-8526-c46cea06632c.png">

**Comment by Miaoyx323** [comment]
Hi, I'm sorry that it is a bug. I have fixed it and uploaded corrected code. Thank you very much for pointing out my mistake.

**Comment by pratapstat** [comment]
Thanks a lot. It's working
