### ISSUE TITLE
infercnv results

### ISSUE THREAD

**Issue by pratapstat** [Miaoyx323/stCancer#6]
Hi,
After running the stCancer package, infercnv was done successfully and cnv heatmap was generated but don't have access to text files results even though in the package there are lines of code were there in package to generate txt files results.
<img width="760" alt="Screenshot 2022-07-28 at 3 08 35 PM" src="https://user-images.githubusercontent.com/8164766/181443757-1123e62e-28dc-4514-9bb7-647ebacf069f.png">
![Screenshot 2022-07-28 at 3 13 00 PM](https://user-images.githubusercontent.com/8164766/181443834-02c9a879-d322-4af1-9cd4-134f218c4bcc.png)

**Comment by pratapstat** [comment]
Hi,

Could i know update regarding this ?

Best Regards,
Pratap

**Comment by Miaoyx323** [comment]
Hi, 

According to the pictures you provided, you used default _copyKAT_ function to analyze CNV and it will not generate the above txt files. You can set _CNV.analysis.func_ of the stAnnotation function to "inferCNV" and provide the reference data of normal tissues to get the results calculated through inferCNV, by which you can get txt files.

We recommend that you use the current default _copykat_ method, which dose not require reference data. The principle of _copykat_ method can be found in this paper, [Delineating copy number and clonal substructure in human tumors from single-cell transcriptomes](https://www.nature.com/articles/s41587-020-00795-2).

Best,
Miao

**Comment by pratapstat** [comment]
Thanks for providing the info and the reference paper.

Best Regards,
Pratap
